name: Branches

on:
  push:
    # branches-ignore: ['main']
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to associate with this run'
        required: true
        type: number

env:
  FORCE_COLOR: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: ${{ github.workflow }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.pr_number && format('refs/pull/{0}/head', github.event.inputs.pr_number) || github.ref }}
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --child-concurrency=10
      # - name: Check
      #   run: pnpm check:ci
      # - name: Test
      #   run: pnpm test:ci
