name: Release

on:
  push:
    branches: ['main']

env:
  FORCE_COLOR: 1

jobs:
  # test-and-deploy:
  #   name: Test and Deploy
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   concurrency: ${{ github.workflow }}
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
  #     - uses: pnpm/action-setup@v4
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: lts/*
  #         cache: 'pnpm'
  #     - name: Install Dependencies
  #       run: pnpm install --frozen-lockfile --child-concurrency=10
  #     - name: Check
  #       run: pnpm check:ci
  #     - name: Test
  #       run: pnpm test:ci
  #     - name: Deploy
  #       run: pnpm turbo deploy
  #       env:
  #         CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #         CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  create-release-pr:
    # For Workers, we always deploy on commits to main.
    # Release PRs are for adding changelogs only (for convenience)
    name: Create Release PR
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: ${{ github.workflow }}-create-release-pr
    permissions:
      contents: write
      pull-requests: write
    outputs:
      published: ${{ steps.create-release-pr.outputs.published }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          # cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --child-concurrency=10 --filter .
      - name: Create Release PR
        id: create-release-pr
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save Published Packages
        if: steps.create-release-pr.outputs.published == 'true'
        run: |
          echo '${{steps.create-release-pr.outputs.publishedPackages}}' > ${{ github.workspace }}/published-packages.json
      - name: Upload Published Packages
        if: steps.create-release-pr.outputs.published == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: published-packages
          path: ${{ github.workspace }}/published-packages.json

  deploy:
    name: Deploy
    needs: create-release-pr
    if: needs.create-release-pr.outputs.published == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download published packages
        uses: actions/download-artifact@v4
        with:
          name: published-packages
          path: ${{ runner.temp }}
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          # cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --child-concurrency=10
      - name: Deploy
        run: |
          cat ${{ runner.temp }}/published-packages.json
          pnpm runx deploy-workers-production
